---
- hosts:
    - localhost
  gather_facts: no
  tasks: 
    - name: Add a host alias 
      add_host:
        hostname: 'bastion_tmp'
        groups: bastion
        ansible_ssh_host: '{{ bastion_private_ip_address }}'
- name: approve csr 
  hosts: bastion_tmp 
  #become: yes
  #become_user: root
  roles:
  - configure-csr
