---
# handlers file for configure-haproxy
- name: turn on haproxy_connect_any
  seboolean: 
    name: haproxy_connect_any
    state: yes
    persistent: yes
  listen: "restart haproxy"

- name: restart haproxy
  service:
    name: haproxy.service
    state: restarted
  listen: "restart haproxy"

- name: Restart firewalld.service
  service:
    name: firewalld.service
    state: restarted
  listen: "restart firewalld"
  

 
