---
# tasks file for create-cluster
- name: Add a host alias 
  add_host:
    hostname: "zvmagent1"
    groups: "zvmagent1"
    ansible_ssh_host: 'item.vm_agent'
  when: item.install_mode == 'zvm'

- name: set fact
  set_fact: 
    host1: "{{item.vm_agent}}"
  when: item.install_mode == 'zvm'
- name: only execute on correct system
  shell: "cat /proc/sysinfo | grep 'VM00 Name:'"
  register: out_node
  when: item.install_mode == 'zvm'

- name: Start up ocp node
  delegate_to: "{{host1}}"
  shell: "/opt/zthin/bin/smcli Image_Activate -T {{ item.vm_uname }}"
  ignore_errors: true
  when: item.install_mode == 'zvm' and "item.vm_node in out_node.stdout"
