---
# tasks file for create-cluster
- name: Add a host alias 
  add_host:
    hostname: "zvmagent1"
    groups: "zvmagent1"
    ansible_ssh_host: 'item.vm_agent'
  when: item.install_mode == 'zkvm'

- name: set fact
  set_fact: 
    host1: "{{item.vm_agent}}"
  when: item.install_mode == 'zkvm'
- name: Start controller installation
  delegate_to: "{{host1}}"
  tags: create_bootstrap
  become: yes
  become_user: root
  ansible.builtin.shell: |
    set -o pipefail
    virsh destroy {{ item.vm_uname }} || true
    virsh undefine {{ item.vm_uname }} --remove-all-storage || true
    virt-install \
    --name {{ item.vm_uname }} \
    --autostart \
    --disk pool={{ item.kvm_vol_grp }},size={{ item.kvm_vol_size }}  \
    --ram 24000 \
    --cpu host \
    --vcpus 4 \
    --network network={{ item.kvm_network }} \
    --location /{{bootfile_dest}}/,kernel=rhcos-4.10.3-s390x-live-kernel-s390x,initrd=rhcos-4.10.3-s390x-live-initramfs.s390x.img \
    --extra-args "rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda \
    coreos.live.rootfs_url=http://{{bastion_private_ip_address}}:8080/rootfs/{{rhcos_disk_image_short}} \
    ip={{ item.ip }}::{{ subnet_gateway }}:{{ subnet_netmask }}:{{ item.hostname }}.{{cluster_domain_name}}::none:1500 \
    nameserver={{ bastion_private_ip_address }} {{ ('--nameserver=' + env.cluster.networking.nameserver2) if env.cluster.networking.nameserver2 is defined else '' }} \
    coreos.inst.ignition_url=http://{{bastion_private_ip_address}}:8080/ignition/master.ign" \
    --graphics none \
    --wait=-1 \
    --noautoconsole
  when: item.install_mode == 'zkvm'